config/routes.rb
Rails.application.routes.draw do
  root 'application#hello'
  resources :custom_visits
  resources :custom_destinations
  resources :creators
  resources :visits
  resources :creations
  resources :destinations
  resources :users
  resources :sessions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/achievement.rb
class Achievement < ApplicationRecord
  belongs_to :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/creation.rb
class Creation < ApplicationRecord
  belongs_to :creator
  belongs_to :destination
end

app/models/creator.rb
class Creator < ApplicationRecord
  has_many :creations
  has_many :destinations, through: :creations
end

app/models/custom_destination.rb
class CustomDestination < ApplicationRecord
  has_many :visits
  has_many :custom_visits
  has_many :users, through: :visits
  has_many :users, through: :custom_visits
end

app/models/custom_visit.rb
class CustomVisit < ApplicationRecord
  belongs_to :user
  belongs_to :custom_destination
end

app/models/destination.rb
class Destination < ApplicationRecord
  has_many :visits
  has_many :users, through: :visits

  def self.most_popular_destination
    hash = Hash.new{0}

    Visit.all.each {|visit| hash[visit.destination_id] += 1}

    most_popular = hash.max_by{|key, val| val}[0]

    Destination.find(most_popular).name
  end


<<<<<<< HEAD
=======

>>>>>>> 001028144a2eb913248a6f68d422e25c34ad6f3c

end

app/models/user.rb
class User < ApplicationRecord
  has_many :visits
  has_many :custom_visits
  has_many :destinations, through: :visits
  has_many :custom_destinations, through: :custom_visits
  has_many :achievements

  validates :user_name, uniqueness: true

  has_secure_password

  attr_reader :password

  def current_user
    session[:user_id] ||= nil
  end

  def full_name
    "#{self.first_name}  #{self.last_name}"
  end
  # def password=(password)
  #   @password = password
  #   salt = BCrypt::Engine::generate_salt
  #   hashed = BCrypt::Engine::hash_secret(password, salt)
  #   self.password_digest = salt + hashed
  # end
  #
  # def authenticate(password)
  #   salt = password_digest[0..28]
  #   hashed = BCrypt::Engine::hash_secret(password, salt)
  #   return nil unless (salt + hashed) == self.password_digest
  #   self
  # end

    def most_recent
      Destination.last.name
    end 

    def first_visited
      Destination.first.name
    end

    def visit_count
      self.visits.count
    end

    def self.most_visits
    hash = Hash.new{0}

    Visit.all.each {|visit| hash[visit.user_id] += 1}

    most_popular = hash.max_by{|key, val| val}[0]
    
    User.find(most_popular).full_name
  end

  def unique_visit_count
    self.destinations.map {|destination| destination.name}.uniq.count
  end

  def self.most_uniq_destinations
    hash = Hash.new{}

    User.all.each {|user| hash[user.id] = user.unique_visit_count}
    
    most_unique_visited = hash.max_by{|key, val| val}[0]

    User.find(most_unique_visited).full_name
  end

end

app/models/visit.rb
class Visit < ApplicationRecord
  belongs_to :user
  belongs_to :destination
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def require_login
    if session[:user_id] == nil
      redirect_to new_session_path
    end
  end

  def stay_in_your_lane
    @user = User.find(params[:id])
      unless session[:user_id] == @user.id
        flash[:error] = "You are not authorized to access that page."
        redirect_to new_session_path
      end
  end

  def current_user
    return unless session[:user_id]
    @current_user ||= User.find(session[:user_id])
  end



end

app/controllers/creations_controller.rb
class CreationsController < ApplicationController

  
end

app/controllers/creators_controller.rb
class CreatorsController < ApplicationController

  def show
    @creator = Creator.new
  end

  def index
    @creators = Creator.all
  end

  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
      @user = User.new
  end

  def create
    @user = User.find_by(user_name: params[:session][:user_name])
    # byebug
      if @user && @user.authenticate(params[:session][:password])
        session[:user_id] = @user.id
        redirect_to user_path(@user)
      else
        flash[:error] = "Invalid login."
        redirect_to new_session_path
      end
    end


  def destroy
    session[:user_id] = nil
    redirect_to new_session_path
  end




end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: [:show, :edit]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    redirect_to @user
  end

  def show
    @user = User.find(params[:id])
      unless session[:user_id] == @user.id
        flash[:error] = "You are not authorized to access that page."
        redirect_to new_session_path
      end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :age, :user_name, :password, :email)
  end

end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController

  def index
    @visits = current_user.visits.all
    @custom_visits = current_user.custom_visits.all
  end

  def new
    @visit = Visit.new
  end

  def show
    @visit = Visit.find(params[:id])
      unless session[:user_id] == @visit.user_id
        flash[:error] = "You are not authorized to access that page."
        redirect_to new_session_path
      end
  end

  def create
    @visit = Visit.create(user_id: current_user.id, destination_id: visit_params[:destination_id], review: visit_params[:review])
    redirect_to user_path(@visit.user_id)
  end

private

  def visit_params
    params.require(:visit).permit(:user_id, :destination_id, :review)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/creations_helper.rb
module CreationsHelper
end

app/helpers/creators_helper.rb
module CreatorsHelper
end

app/helpers/custom_destinations_helper.rb
module CustomDestinationsHelper
end

app/helpers/custom_visits_helper.rb
module CustomVisitsHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/users/new.html.erb
<%= form_for(@user) do |f| %>
<%= f.label :first_name%>
<%= f.text_field :first_name %><br>
<%= f.label :last_name%>
<%= f.text_field :last_name %><br>
<%= f.label :age %>
<%= f.number_field :age %><br>
<%= f.label :user_name %>
<%= f.text_field :user_name %><br>
<%= f.label :password %>
<%= f.password_field :password %><br>
<%= f.label :email  %>
<%= f.text_field :email %><br>
<%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1>Your NYSee Account</h1>

<div class="user_profile">
<%= @user.first_name %> <%= @user.last_name %><br>
Age: <%= @user.age %><br>
Username: <%= @user.user_name %><br>
<%= @user.email %><br>

<%= link_to "Create a New Visit", new_visit_path %><br>
<br>
<%= link_to "All My Visits", visits_path %><br>
<br>
<%= button_to "Log Out", session_path, method: :delete %>
</div>

app/views/visits/index.html.erb
<h1>My Visited Places:</h1>
<div class="visits_display">
<% @visits.each do |v| %>
<li><%= link_to v.destination.name, destination_path(v.destination_id) %></li>
<% end %>
<% @custom_visits.each do |v| %>
<li><%= link_to v.custom_destination.name, custom_destination_path(v.custom_destination_path) %></li>
<% end %><br>
</div>
<%= button_to "Back To My Profile", user_path(session[:user_id]), :method => "get" %>

app/views/visits/new.html.erb
<h1>Create a New Visit!</h1><br>

<h2>Choose a Destination:</h2>
<%= form_for @visit do |f| %>
<%= f.collection_select :destination_id, Destination.all, :id, :name %>
<%= f.submit %>
<% end %><br>
<br>




<%= link_to "OR Create Your Own Destination!", new_custom_destination_path %><br>
<br>

<%= button_to "Back To My Profile", user_path(session[:user_id]), :method => "get" %>

app/views/visits/show.html.erb
<%= @visit.destination.name %>